// Code generated by "go generate"; DO NOT EDIT.

package paths

import (
	"fmt"

	"github.com/leg100/otf/internal/resource"
)

func Organizations() string {
	return "/app/organizations"
}

func CreateOrganization() string {
	return "/app/organizations/create"
}

func NewOrganization() string {
	return "/app/organizations/new"
}

func Organization(organization resource.ID) string {
	return fmt.Sprintf("/app/organizations/%s", organization)
}

func EditOrganization(organization resource.ID) string {
	return fmt.Sprintf("/app/organizations/%s/edit", organization)
}

func UpdateOrganization(organization resource.ID) string {
	return fmt.Sprintf("/app/organizations/%s/update", organization)
}

func DeleteOrganization(organization resource.ID) string {
	return fmt.Sprintf("/app/organizations/%s/delete", organization)
}
