builds:
  - id: otfd
    ldflags:
    - -s -w
    - -X github.com/leg100/otf/internal.Version={{.Version}}
    - -X github.com/leg100/otf/internal.Commit={{.Commit}}
    - -X github.com/leg100/otf/internal.Built={{.Date}}
    main: ./cmd/otfd
    binary: otfd
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - 386
    - amd64
    - arm64
  - id: otf-agent
    ldflags:
    - -s -w
    - -X github.com/leg100/otf/internal.Version={{.Version}}
    - -X github.com/leg100/otf/internal.Commit={{.Commit}}
    - -X github.com/leg100/otf/internal.Built={{.Date}}
    main: ./cmd/otf-agent
    binary: otf-agent
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - 386
    - amd64
    - arm64
  - id: otf
    ldflags:
    - -s -w
    - -X github.com/leg100/otf/internal.Version={{.Version}}
    - -X github.com/leg100/otf/internal.Commit={{.Commit}}
    - -X github.com/leg100/otf/internal.Built={{.Date}}
    main: ./cmd/otf
    binary: otf
    env:
      - CGO_ENABLED=0
    goos:
    - darwin
    - linux
    goarch:
    - 386
    - amd64
    - arm64
archives:
- id: otfd
  builds:
    - otfd
  format: zip
  name_template: "otfd_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: otf-agent
  builds:
    - otf-agent
  format: zip
  name_template: "otf-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: otf
  builds:
    - otf
  format: zip
  name_template: "otf_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
dockers:
- goos: linux
  goarch: amd64
  ids:
  - otfd
  image_templates:
  - "leg100/otfd:latest"
  - "leg100/otfd:{{ .Version }}"
  skip_push: auto
  dockerfile: Dockerfile
- goos: linux
  goarch: amd64
  ids:
  - otf-agent
  image_templates:
  - "leg100/otf-agent:latest"
  - "leg100/otf-agent:{{ .Version }}"
  skip_push: auto
  dockerfile: Dockerfile.agent
release:
  footer: |
    ## Docker images

    * `leg100/otfd:{{ .Version }}`
    * `leg100/otf-agent:{{ .Version }}`
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
