builds:
  - id: otfd
    ldflags:
    - -s
    - '-X ".Version={{ .Version }}"'
    - '-X ".Commit={{ .Commit }}"'
    main: ./cmd/otfd
    binary: otfd
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    goarch:
    - 386
    - amd64
    - arm64
  - id: otf
    ldflags:
    - -s
    - '-X ".Version={{ .Version }}"'
    - '-X ".Commit={{ .Commit }}"'
    main: ./cmd/otf
    binary: otf
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    goarch:
    - 386
    - amd64
    - arm64
archives:
- format: zip
  files:
  - none*
dockers:
- goos: linux
  goarch: amd64
  ids:
  - otfd
  image_templates:
  - "leg100/otf:latest"
  - "leg100/otf:{{ .Version }}"
  skip_push: auto
  dockerfile: Dockerfile
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
