version: 2
builds:
  - id: otfd
    ldflags:
    - -s -w
    - -X github.com/leg100/otf/internal.Version={{.Version}}
    - -X github.com/leg100/otf/internal.Commit={{.Commit}}
    - -X github.com/leg100/otf/internal.Built={{.Date}}
    main: ./cmd/otfd
    binary: otfd
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - amd64
    - arm64
  - id: otf-agent
    ldflags:
    - -s -w
    - -X github.com/leg100/otf/internal.Version={{.Version}}
    - -X github.com/leg100/otf/internal.Commit={{.Commit}}
    - -X github.com/leg100/otf/internal.Built={{.Date}}
    main: ./cmd/otf-agent
    binary: otf-agent
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - amd64
    - arm64
  - id: otf-job
    ldflags:
    - -s -w
    - -X github.com/leg100/otf/internal.Version={{.Version}}
    - -X github.com/leg100/otf/internal.Commit={{.Commit}}
    - -X github.com/leg100/otf/internal.Built={{.Date}}
    main: ./cmd/otf-job
    binary: otf-job
    env:
      - CGO_ENABLED=0
    goos:
    - darwin
    - linux
    goarch:
    - amd64
    - arm64
archives:
- id: otfd
  ids: [otfd]
  formats: [zip]
  name_template: "otfd_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: otf-agent
  ids: [otf-agent]
  formats: [zip]
  name_template: "otf-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: otf-job
  ids: [otf-job]
  formats: [zip]
  name_template: "otf-job_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
dockers_v2:
- id: otfd
  ids: [otfd]
  images:
    - leg100/otfd
  tags:
  - "latest"
  - "edge"
  - "{{ .Version }}"
  platforms:
    - linux/amd64
    - linux/arm64
  flags: ["--target", "otfd"]
  sbom: false
- id: otf-agent
  ids: [otf-agent]
  images:
    - leg100/otf-agent
  tags:
  - "latest"
  - "edge"
  - "{{ .Version }}"
  platforms:
    - linux/amd64
    - linux/arm64
  flags: ["--target", "otf-agent"]
  sbom: false
- id: otf-job
  ids: [otf-job]
  images:
    - leg100/otf-job
  tags:
  - "latest"
  - "edge"
  - "{{ .Version }}"
  platforms:
    - linux/amd64
    - linux/arm64
  flags: ["--target", "otf-job"]
  sbom: false
checksum:
  name_template: 'checksums.txt'
changelog:
  disable: true
