# run postgres in a container and wait for it to fully start
services:
  database:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -c fsync=off
    container_name: postgres
    environment:
     - POSTGRES_PASSWORD=postgres
  wait:
    image: alpine
    depends_on:
      database:
        condition: service_healthy
