openapi: 3.1.0
info:
  title: OTF API
  description: OTF API documentation
  contact:
    name: Louis Garman
    email: louisgarman@gmail.com
  license:
    name: Mozilla Public License
    url: https://www.mozilla.org/en-US/MPL/
  version: 1.0.0
tags:
  - name: User and Authentication
  - name: Organizations
  - name: Workspaces
servers:
  - url: /otfapi/v2
    description: Base path
paths:
  /login/clients:
    get:
      summary: Get login clients
      description: Get available OAuth clients for login.
      tags:
        - User and Authentication
      operationId: getLoginClients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /current-user:
    get:
      summary: Get current user
      description: Get the currently logged in user
      tags:
        - User and Authentication
      operationId: getCurrentUser
      responses:
        '200':
          description: OK
          application/json:
            schema: "#/components/schemas/User"
        '401':
          $ref: '#/components/responses/Unauthorized'
  /organizations:
    get:
      summary: Get organizations
      description: Get a list of organizations
      tags:
        - Organizations
      operationId: getOrganizations
      parameters:
        - $ref: "#/components/parameters/page_number"
        - $ref: "#/components/parameters/page_size"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Organization'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /organizations/{organization}:
    get:
      summary: Get organization
      description: Get an organization
      tags:
        - Organizations
      operationId: getOrganization
      parameters:
        - name: organization
          description: Name of organization
          in: path
          schema:
            type: string
      responses:
        '200':
          description: OK
          application/json:
            schema: "#/components/schemas/Organization"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Client:
      description: Login client
      type: object
      properties:
        name:
          type: string
        logo:
          type: string
        requestPath:
          type: string
    Organization:
      description: Organization
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Workspace:
      description: Workspace
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        organization:
          type: string
        terraformVersion:
          type: string
    User:
      required:
        - username
      type: object
      properties:
        username:
          type: string
        isSiteAdmin:
          type: boolean
    Pagination:
      required:
        - current_page
        - total_pages
        - total_count
      type: object
      properties:
        current_page:
          type: integer
        previous_page:
          type: integer
        next_page:
          type: integer
        total_pages:
          type: integer
        total_count:
          type: integer
  responses:
    EmptyOkResponse:
      description: No content
      content: {}
    Unauthorized:
      description: Unauthorized
      content: {}
    InternalServerError:
      description: Unexpected server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required:
              - error
  parameters:
    page_number:
      name: page_number
      in: query
      description: Request ordinal page number.
      required: false
      schema:
        type: integer
        minimum: 1
    page_size:
      name: page_size
      in: query
      description: Request max number of items on page.
      required: false
      schema:
        type: integer
        minimum: 10
        maximum: 100
        default: 20
