#!/usr/bin/env bash

cat > /etc/apt/apt.conf.d/00qbe <<EOT
// When apt installs or upgrades a package and encounters an existing config file on
// disk that the operation would overwrite, apt prompts for user input as to what to do.
// The configuration below instructs apt to disable this prompt and automatically skip
// overwrites.
//
// By setting this, we ensure that both (a) our custom config files are retained, and (b)
// non-interactive apt operations are not blocked, e.g. by the GCP OS patch management agent.
//
// See: https://debian-handbook.info/browse/stable/sect.package-meta-information.html#sidebar.questions-conffiles
DPkg::options {
  "--force-confdef";
  "--force-confold";
}
EOT

