{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "otf.fullname" . }}
  labels:
    {{- include "otf.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "otf.labels" . | nindent 6 }}
  endpoints:
  - port: http
{{- end }}
