repositories:
  - name: cloudnative-pg
    url: https://cloudnative-pg.github.io/charts

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: otf
    namespace: default
    chart: ../chart
    needs:
      - postgres
    values:
    - values/otf.gotmpl

  - name: cloudnative-pg
    namespace: cnpg-system
    chart: cloudnative-pg/cloudnative-pg
    version: 0.15.1

  - name: otf-dashboard
    namespace: monitoring
    chart: ./charts/otf-dashboard

  - name: cloudnative-pg-dashboard
    namespace: monitoring
    chart: cloudnative-pg/cnpg-sandbox
    version: 0.6.1
    disableValidationOnInstall: true
    needs:
      - monitoring/prometheus
    set:
    - name: kube-prometheus-stack.enabled
      value: false
    - name: cloudnative-pg.enabled
      value: false

  - name: postgres
    namespace: default
    chart: ./charts/postgres
    disableValidationOnInstall: true
    needs:
      - cnpg-system/cloudnative-pg
    labels:
      release: postgres

  - name: ingress-nginx
    chart: ./charts/kind-ingress-nginx
    version: 4.3.0

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.10.0
    set:
    - name: installCRDs
      value: true
    - name: ingressShim.defaultIssuerName
      value: letsencrypt-prod
    - name: ingressShim.defaultIssuerKind
      value: ClusterIssuer
    - name: ingressShim.defaultIssuerGroup
      value: cert-manager.io

  - name: cert-manager-issuer
    chart: ./charts/cert-manager-issuer
    disableValidationOnInstall: true
    needs:
      - cert-manager/cert-manager
    set:
    - name: email
      value: {{ requiredEnv "EMAIL" }}

  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 41.6.1
    disableValidation: true
    values:
      - values/kube-prometheus-stack.gotmpl
      - prometheus:
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false

helmDefaults:
  # wait for k8s resources via --wait
  wait: true
  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness)
  timeout: 300

