// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"internal/run/run"
)

type Agent struct {
	AgentID      string
	Name         string
	Version      string
	MaxJobs      int32
	IpAddress    netip.Addr
	LastPingAt   pgtype.Timestamptz
	LastStatusAt pgtype.Timestamptz
	Status       string
	AgentPoolID  pgtype.Text
}

type AgentPool struct {
	AgentPoolID        string
	Name               string
	CreatedAt          pgtype.Timestamptz
	OrganizationName   string
	OrganizationScoped bool
}

type AgentPoolAllowedWorkspace struct {
	AgentPoolID string
	WorkspaceID string
}

type AgentStatus struct {
	Status string
}

type AgentToken struct {
	AgentTokenID string
	CreatedAt    pgtype.Timestamptz
	Description  string
	AgentPoolID  string
}

type Apply struct {
	RunID          string
	Status         string
	ResourceReport run.Report
}

type ConfigurationVersion struct {
	ConfigurationVersionID string
	CreatedAt              pgtype.Timestamptz
	AutoQueueRuns          bool
	Source                 string
	Speculative            bool
	Status                 string
	Config                 []byte
	WorkspaceID            string
}

type ConfigurationVersionIngressAttribute struct {
	Branch                 string
	CommitSha              string
	Identifier             string
	IsPullRequest          bool
	OnDefaultBranch        bool
	ConfigurationVersionID string
	CommitUrl              string
	PullRequestNumber      int32
	PullRequestUrl         string
	PullRequestTitle       string
	Tag                    string
	SenderUsername         string
	SenderAvatarUrl        string
	SenderHtmlUrl          string
}

type ConfigurationVersionStatusTimestamp struct {
	ConfigurationVersionID string
	Status                 string
	Timestamp              pgtype.Timestamptz
}

type DestinationType struct {
	Name string
}

type GithubApp struct {
	GithubAppID   int64
	WebhookSecret string
	PrivateKey    string
	Slug          string
	Organization  pgtype.Text
}

type GithubAppInstall struct {
	GithubAppID   int64
	InstallID     int64
	Username      pgtype.Text
	Organization  pgtype.Text
	VcsProviderID string
}

type IngressAttribute struct {
	Branch                 string
	CommitSha              string
	Identifier             string
	IsPullRequest          bool
	OnDefaultBranch        bool
	ConfigurationVersionID string
	CommitUrl              string
	PullRequestNumber      int32
	PullRequestUrl         string
	PullRequestTitle       string
	Tag                    string
	SenderUsername         string
	SenderAvatarUrl        string
	SenderHtmlUrl          string
}

type Job struct {
	RunID    string
	Phase    string
	Status   string
	AgentID  pgtype.Text
	Signaled pgtype.Bool
}

type JobPhase struct {
	Phase string
}

type JobStatus struct {
	Status string
}

type LatestTerraformVersion struct {
	Version    string
	Checkpoint pgtype.Timestamptz
}

type Log struct {
	RunID   string
	Phase   string
	ChunkID pgtype.Int4
	Chunk   []byte
	Offset  int32
}

type Module struct {
	ModuleID         string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Name             string
	Provider         string
	Status           string
	OrganizationName string
}

type ModuleStatus struct {
	Status string
}

type ModuleTarball struct {
	Tarball         []byte
	ModuleVersionID string
}

type ModuleVersion struct {
	ModuleVersionID string
	Version         string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Status          string
	StatusError     pgtype.Text
	ModuleID        string
}

type ModuleVersionStatus struct {
	Status string
}

type NotificationConfiguration struct {
	NotificationConfigurationID string
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	Name                        string
	Url                         pgtype.Text
	Triggers                    []string
	DestinationType             string
	WorkspaceID                 string
	Enabled                     bool
}

type Organization struct {
	OrganizationID             string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	Name                       string
	SessionRemember            pgtype.Int4
	SessionTimeout             pgtype.Int4
	Email                      pgtype.Text
	CollaboratorAuthPolicy     pgtype.Text
	AllowForceDeleteWorkspaces bool
	CostEstimationEnabled      bool
}

type OrganizationToken struct {
	OrganizationTokenID string
	CreatedAt           pgtype.Timestamptz
	OrganizationName    string
	Expiry              pgtype.Timestamptz
}

type Phase struct {
	Phase string
}

type PhaseStatus struct {
	Status string
}

type PhaseStatusTimestamp struct {
	RunID     string
	Phase     string
	Status    string
	Timestamp pgtype.Timestamptz
}

type Plan struct {
	RunID          string
	Status         string
	PlanBin        []byte
	PlanJson       []byte
	ResourceReport run.Report
	OutputReport   run.Report
}

type RegistrySession struct {
	Token            string
	Expiry           pgtype.Timestamptz
	OrganizationName string
}

type RepoConnection struct {
	ModuleID      pgtype.Text
	WorkspaceID   pgtype.Text
	RepoPath      string
	VcsProviderID string
}

type Repohook struct {
	RepohookID    pgtype.UUID
	VcsID         pgtype.Text
	Secret        string
	RepoPath      string
	VcsProviderID string
}

type Run struct {
	RunID                  string
	CreatedAt              pgtype.Timestamptz
	CancelSignaledAt       pgtype.Timestamptz
	IsDestroy              bool
	PositionInQueue        int32
	Refresh                bool
	RefreshOnly            bool
	ReplaceAddrs           []string
	TargetAddrs            []string
	LockFile               []byte
	Status                 string
	WorkspaceID            string
	ConfigurationVersionID string
	AutoApply              bool
	PlanOnly               bool
	CreatedBy              pgtype.Text
	Source                 string
	TerraformVersion       string
	AllowEmptyApply        bool
}

type RunStatus struct {
	Status string
}

type RunStatusTimestamp struct {
	RunID     string
	Status    string
	Timestamp pgtype.Timestamptz
}

type RunVariable struct {
	RunID string
	Key   string
	Value string
}

type SchemaVersion struct {
	Version int32
}

type Session struct {
	Token     string
	CreatedAt pgtype.Timestamptz
	Address   string
	Expiry    pgtype.Timestamptz
	Username  string
}

type StateVersion struct {
	StateVersionID string
	CreatedAt      pgtype.Timestamptz
	Serial         int32
	State          []byte
	WorkspaceID    pgtype.Text
	Status         string
}

type StateVersionOutput struct {
	StateVersionOutputID string
	Name                 string
	Sensitive            bool
	Type                 string
	Value                []byte
	StateVersionID       string
}

type StateVersionStatus struct {
	Status string
}

type Tag struct {
	TagID            string
	Name             string
	OrganizationName string
}

type Team struct {
	TeamID                          string
	Name                            string
	CreatedAt                       pgtype.Timestamptz
	PermissionManageWorkspaces      bool
	PermissionManageVcs             bool
	PermissionManageModules         bool
	OrganizationName                string
	SsoTeamID                       pgtype.Text
	Visibility                      string
	PermissionManagePolicies        bool
	PermissionManagePolicyOverrides bool
	PermissionManageProviders       bool
}

type TeamMembership struct {
	TeamID   string
	Username string
}

type TeamToken struct {
	TeamTokenID string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	TeamID      string
	Expiry      pgtype.Timestamptz
}

type Token struct {
	TokenID     string
	CreatedAt   pgtype.Timestamptz
	Description string
	Username    string
}

type User struct {
	UserID    string
	Username  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	SiteAdmin bool
}

type Variable struct {
	VariableID  string
	Key         string
	Value       string
	Description string
	Category    string
	Sensitive   bool
	Hcl         bool
	VersionID   string
}

type VariableCategory struct {
	Category string
}

type VariableSet struct {
	VariableSetID    string
	Global           bool
	Name             string
	Description      string
	OrganizationName string
}

type VariableSetVariable struct {
	VariableSetID string
	VariableID    string
}

type VariableSetWorkspace struct {
	VariableSetID string
	WorkspaceID   string
}

type VcsKind struct {
	Name string
}

type VcsProvider struct {
	VcsProviderID    string
	Token            pgtype.Text
	CreatedAt        pgtype.Timestamptz
	Name             string
	VcsKind          string
	OrganizationName string
	GithubAppID      pgtype.Int8
}

type Workspace struct {
	WorkspaceID                string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	AllowDestroyPlan           bool
	AutoApply                  bool
	CanQueueDestroyPlan        bool
	Description                string
	Environment                string
	ExecutionMode              string
	GlobalRemoteState          bool
	MigrationEnvironment       string
	Name                       string
	QueueAllRuns               bool
	SpeculativeEnabled         bool
	SourceName                 string
	SourceUrl                  string
	StructuredRunOutputEnabled bool
	TerraformVersion           string
	TriggerPrefixes            []string
	WorkingDirectory           string
	LockRunID                  pgtype.Text
	LatestRunID                pgtype.Text
	OrganizationName           string
	Branch                     string
	LockUsername               pgtype.Text
	CurrentStateVersionID      pgtype.Text
	TriggerPatterns            []string
	VcsTagsRegex               pgtype.Text
	AllowCliApply              bool
	AgentPoolID                pgtype.Text
}

type WorkspacePermission struct {
	WorkspaceID string
	TeamID      string
	Role        string
}

type WorkspaceRole struct {
	Role string
}

type WorkspaceTag struct {
	TagID       string
	WorkspaceID string
}

type WorkspaceVariable struct {
	WorkspaceID string
	VariableID  string
}
