// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package notifications

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/leg100/otf/internal/resource"
)

type ConfigModel struct {
	NotificationConfigurationID resource.ID
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	Name                        pgtype.Text
	URL                         pgtype.Text
	Triggers                    []pgtype.Text
	DestinationType             pgtype.Text
	WorkspaceID                 resource.ID
	Enabled                     pgtype.Bool
}
