// Code generated by pggen. DO NOT EDIT.

package pggen

import (
	"context"
	"fmt"

	"github.com/jackc/pgconn"
	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

const insertGithubAppSQL = `INSERT INTO github_apps (
    github_app_id,
    webhook_secret,
    private_key,
    organization_name
) VALUES (
    $1,
    $2,
    $3,
    $4
);`

type InsertGithubAppParams struct {
	GithubAppID      pgtype.Int8
	WebhookSecret    pgtype.Text
	PrivateKey       pgtype.Text
	OrganizationName pgtype.Text
}

// InsertGithubApp implements Querier.InsertGithubApp.
func (q *DBQuerier) InsertGithubApp(ctx context.Context, params InsertGithubAppParams) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "InsertGithubApp")
	cmdTag, err := q.conn.Exec(ctx, insertGithubAppSQL, params.GithubAppID, params.WebhookSecret, params.PrivateKey, params.OrganizationName)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query InsertGithubApp: %w", err)
	}
	return cmdTag, err
}

// InsertGithubAppBatch implements Querier.InsertGithubAppBatch.
func (q *DBQuerier) InsertGithubAppBatch(batch genericBatch, params InsertGithubAppParams) {
	batch.Queue(insertGithubAppSQL, params.GithubAppID, params.WebhookSecret, params.PrivateKey, params.OrganizationName)
}

// InsertGithubAppScan implements Querier.InsertGithubAppScan.
func (q *DBQuerier) InsertGithubAppScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec InsertGithubAppBatch: %w", err)
	}
	return cmdTag, err
}

const findGithubAppsByOrganizationSQL = `SELECT *
FROM github_apps
WHERE organization_name = $1;`

type FindGithubAppsByOrganizationRow struct {
	GithubAppID      pgtype.Int8 `json:"github_app_id"`
	WebhookSecret    pgtype.Text `json:"webhook_secret"`
	PrivateKey       pgtype.Text `json:"private_key"`
	OrganizationName pgtype.Text `json:"organization_name"`
}

// FindGithubAppsByOrganization implements Querier.FindGithubAppsByOrganization.
func (q *DBQuerier) FindGithubAppsByOrganization(ctx context.Context, organizationName pgtype.Text) (FindGithubAppsByOrganizationRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindGithubAppsByOrganization")
	row := q.conn.QueryRow(ctx, findGithubAppsByOrganizationSQL, organizationName)
	var item FindGithubAppsByOrganizationRow
	if err := row.Scan(&item.GithubAppID, &item.WebhookSecret, &item.PrivateKey, &item.OrganizationName); err != nil {
		return item, fmt.Errorf("query FindGithubAppsByOrganization: %w", err)
	}
	return item, nil
}

// FindGithubAppsByOrganizationBatch implements Querier.FindGithubAppsByOrganizationBatch.
func (q *DBQuerier) FindGithubAppsByOrganizationBatch(batch genericBatch, organizationName pgtype.Text) {
	batch.Queue(findGithubAppsByOrganizationSQL, organizationName)
}

// FindGithubAppsByOrganizationScan implements Querier.FindGithubAppsByOrganizationScan.
func (q *DBQuerier) FindGithubAppsByOrganizationScan(results pgx.BatchResults) (FindGithubAppsByOrganizationRow, error) {
	row := results.QueryRow()
	var item FindGithubAppsByOrganizationRow
	if err := row.Scan(&item.GithubAppID, &item.WebhookSecret, &item.PrivateKey, &item.OrganizationName); err != nil {
		return item, fmt.Errorf("scan FindGithubAppsByOrganizationBatch row: %w", err)
	}
	return item, nil
}

const findGithubAppByIDSQL = `SELECT *
FROM github_apps
WHERE github_app_id = $1;`

type FindGithubAppByIDRow struct {
	GithubAppID      pgtype.Int8 `json:"github_app_id"`
	WebhookSecret    pgtype.Text `json:"webhook_secret"`
	PrivateKey       pgtype.Text `json:"private_key"`
	OrganizationName pgtype.Text `json:"organization_name"`
}

// FindGithubAppByID implements Querier.FindGithubAppByID.
func (q *DBQuerier) FindGithubAppByID(ctx context.Context, githubAppID pgtype.Int8) (FindGithubAppByIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindGithubAppByID")
	row := q.conn.QueryRow(ctx, findGithubAppByIDSQL, githubAppID)
	var item FindGithubAppByIDRow
	if err := row.Scan(&item.GithubAppID, &item.WebhookSecret, &item.PrivateKey, &item.OrganizationName); err != nil {
		return item, fmt.Errorf("query FindGithubAppByID: %w", err)
	}
	return item, nil
}

// FindGithubAppByIDBatch implements Querier.FindGithubAppByIDBatch.
func (q *DBQuerier) FindGithubAppByIDBatch(batch genericBatch, githubAppID pgtype.Int8) {
	batch.Queue(findGithubAppByIDSQL, githubAppID)
}

// FindGithubAppByIDScan implements Querier.FindGithubAppByIDScan.
func (q *DBQuerier) FindGithubAppByIDScan(results pgx.BatchResults) (FindGithubAppByIDRow, error) {
	row := results.QueryRow()
	var item FindGithubAppByIDRow
	if err := row.Scan(&item.GithubAppID, &item.WebhookSecret, &item.PrivateKey, &item.OrganizationName); err != nil {
		return item, fmt.Errorf("scan FindGithubAppByIDBatch row: %w", err)
	}
	return item, nil
}

const deleteGithubAppByIDSQL = `DELETE
FROM github_apps
WHERE github_app_id = $1
RETURNING *;`

type DeleteGithubAppByIDRow struct {
	GithubAppID      pgtype.Int8 `json:"github_app_id"`
	WebhookSecret    pgtype.Text `json:"webhook_secret"`
	PrivateKey       pgtype.Text `json:"private_key"`
	OrganizationName pgtype.Text `json:"organization_name"`
}

// DeleteGithubAppByID implements Querier.DeleteGithubAppByID.
func (q *DBQuerier) DeleteGithubAppByID(ctx context.Context, githubAppID pgtype.Int8) (DeleteGithubAppByIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "DeleteGithubAppByID")
	row := q.conn.QueryRow(ctx, deleteGithubAppByIDSQL, githubAppID)
	var item DeleteGithubAppByIDRow
	if err := row.Scan(&item.GithubAppID, &item.WebhookSecret, &item.PrivateKey, &item.OrganizationName); err != nil {
		return item, fmt.Errorf("query DeleteGithubAppByID: %w", err)
	}
	return item, nil
}

// DeleteGithubAppByIDBatch implements Querier.DeleteGithubAppByIDBatch.
func (q *DBQuerier) DeleteGithubAppByIDBatch(batch genericBatch, githubAppID pgtype.Int8) {
	batch.Queue(deleteGithubAppByIDSQL, githubAppID)
}

// DeleteGithubAppByIDScan implements Querier.DeleteGithubAppByIDScan.
func (q *DBQuerier) DeleteGithubAppByIDScan(results pgx.BatchResults) (DeleteGithubAppByIDRow, error) {
	row := results.QueryRow()
	var item DeleteGithubAppByIDRow
	if err := row.Scan(&item.GithubAppID, &item.WebhookSecret, &item.PrivateKey, &item.OrganizationName); err != nil {
		return item, fmt.Errorf("scan DeleteGithubAppByIDBatch row: %w", err)
	}
	return item, nil
}

const insertGithubAppInstallSQL = `INSERT INTO github_app_installs (
    github_app_install_id,
    github_app_id
) VALUES (
    $1,
    $2
);`

// InsertGithubAppInstall implements Querier.InsertGithubAppInstall.
func (q *DBQuerier) InsertGithubAppInstall(ctx context.Context, githubAppInstallID pgtype.Int8, githubAppID pgtype.Int8) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "InsertGithubAppInstall")
	cmdTag, err := q.conn.Exec(ctx, insertGithubAppInstallSQL, githubAppInstallID, githubAppID)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query InsertGithubAppInstall: %w", err)
	}
	return cmdTag, err
}

// InsertGithubAppInstallBatch implements Querier.InsertGithubAppInstallBatch.
func (q *DBQuerier) InsertGithubAppInstallBatch(batch genericBatch, githubAppInstallID pgtype.Int8, githubAppID pgtype.Int8) {
	batch.Queue(insertGithubAppInstallSQL, githubAppInstallID, githubAppID)
}

// InsertGithubAppInstallScan implements Querier.InsertGithubAppInstallScan.
func (q *DBQuerier) InsertGithubAppInstallScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec InsertGithubAppInstallBatch: %w", err)
	}
	return cmdTag, err
}

const findGithubAppInstallByIDSQL = `SELECT *
FROM github_app_installs
JOIN github_apps USING (github_app_id)
WHERE github_app_install_id = $1;`

type FindGithubAppInstallByIDRow struct {
	GithubAppID        pgtype.Int8 `json:"github_app_id"`
	GithubAppInstallID pgtype.Int8 `json:"github_app_install_id"`
	WebhookSecret      pgtype.Text `json:"webhook_secret"`
	PrivateKey         pgtype.Text `json:"private_key"`
	OrganizationName   pgtype.Text `json:"organization_name"`
}

// FindGithubAppInstallByID implements Querier.FindGithubAppInstallByID.
func (q *DBQuerier) FindGithubAppInstallByID(ctx context.Context, githubAppInstallID pgtype.Int8) (FindGithubAppInstallByIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindGithubAppInstallByID")
	row := q.conn.QueryRow(ctx, findGithubAppInstallByIDSQL, githubAppInstallID)
	var item FindGithubAppInstallByIDRow
	if err := row.Scan(&item.GithubAppID, &item.GithubAppInstallID, &item.WebhookSecret, &item.PrivateKey, &item.OrganizationName); err != nil {
		return item, fmt.Errorf("query FindGithubAppInstallByID: %w", err)
	}
	return item, nil
}

// FindGithubAppInstallByIDBatch implements Querier.FindGithubAppInstallByIDBatch.
func (q *DBQuerier) FindGithubAppInstallByIDBatch(batch genericBatch, githubAppInstallID pgtype.Int8) {
	batch.Queue(findGithubAppInstallByIDSQL, githubAppInstallID)
}

// FindGithubAppInstallByIDScan implements Querier.FindGithubAppInstallByIDScan.
func (q *DBQuerier) FindGithubAppInstallByIDScan(results pgx.BatchResults) (FindGithubAppInstallByIDRow, error) {
	row := results.QueryRow()
	var item FindGithubAppInstallByIDRow
	if err := row.Scan(&item.GithubAppID, &item.GithubAppInstallID, &item.WebhookSecret, &item.PrivateKey, &item.OrganizationName); err != nil {
		return item, fmt.Errorf("scan FindGithubAppInstallByIDBatch row: %w", err)
	}
	return item, nil
}

const deleteGithubAppInstallByIDSQL = `DELETE
FROM github_app_installs
WHERE github_app_install_id = $1
RETURNING *;`

type DeleteGithubAppInstallByIDRow struct {
	GithubAppInstallID pgtype.Int8 `json:"github_app_install_id"`
	GithubAppID        pgtype.Int8 `json:"github_app_id"`
}

// DeleteGithubAppInstallByID implements Querier.DeleteGithubAppInstallByID.
func (q *DBQuerier) DeleteGithubAppInstallByID(ctx context.Context, githubAppInstallID pgtype.Int8) (DeleteGithubAppInstallByIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "DeleteGithubAppInstallByID")
	row := q.conn.QueryRow(ctx, deleteGithubAppInstallByIDSQL, githubAppInstallID)
	var item DeleteGithubAppInstallByIDRow
	if err := row.Scan(&item.GithubAppInstallID, &item.GithubAppID); err != nil {
		return item, fmt.Errorf("query DeleteGithubAppInstallByID: %w", err)
	}
	return item, nil
}

// DeleteGithubAppInstallByIDBatch implements Querier.DeleteGithubAppInstallByIDBatch.
func (q *DBQuerier) DeleteGithubAppInstallByIDBatch(batch genericBatch, githubAppInstallID pgtype.Int8) {
	batch.Queue(deleteGithubAppInstallByIDSQL, githubAppInstallID)
}

// DeleteGithubAppInstallByIDScan implements Querier.DeleteGithubAppInstallByIDScan.
func (q *DBQuerier) DeleteGithubAppInstallByIDScan(results pgx.BatchResults) (DeleteGithubAppInstallByIDRow, error) {
	row := results.QueryRow()
	var item DeleteGithubAppInstallByIDRow
	if err := row.Scan(&item.GithubAppInstallID, &item.GithubAppID); err != nil {
		return item, fmt.Errorf("scan DeleteGithubAppInstallByIDBatch row: %w", err)
	}
	return item, nil
}
