// Code generated by pggen. DO NOT EDIT.

package sql

import (
	"context"
	"fmt"
	"github.com/jackc/pgconn"
	"github.com/jackc/pgx/v4"
	"github.com/leg100/otf"
	"time"
)

const insertRunSQL = `INSERT INTO runs (
    run_id,
    plan_id,
    apply_id,
    created_at,
    updated_at,
    is_destroy,
    position_in_queue,
    refresh,
    refresh_only,
    status,
    plan_status,
    apply_status,
    replace_addrs,
    target_addrs,
    configuration_version_id,
    workspace_id
) VALUES (
    $1,
    $2,
    $3,
    current_timestamp,
    current_timestamp,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING *;`

type InsertRunParams struct {
	ID                     string
	PlanID                 string
	ApplyID                string
	IsDestroy              bool
	PositionInQueue        int32
	Refresh                bool
	RefreshOnly            bool
	Status                 string
	PlanStatus             string
	ApplyStatus            string
	ReplaceAddrs           []string
	TargetAddrs            []string
	ConfigurationVersionID string
	WorkspaceID            string
}

type InsertRunRow struct {
	RunID                  string    `json:"run_id"`
	PlanID                 string    `json:"plan_id"`
	ApplyID                string    `json:"apply_id"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
	IsDestroy              bool      `json:"is_destroy"`
	PositionInQueue        int32     `json:"position_in_queue"`
	Refresh                bool      `json:"refresh"`
	RefreshOnly            bool      `json:"refresh_only"`
	Status                 string    `json:"status"`
	ReplaceAddrs           []string  `json:"replace_addrs"`
	TargetAddrs            []string  `json:"target_addrs"`
	PlanStatus             string    `json:"plan_status"`
	PlanBin                []byte    `json:"plan_bin"`
	PlanJson               []byte    `json:"plan_json"`
	ApplyStatus            string    `json:"apply_status"`
	WorkspaceID            string    `json:"workspace_id"`
	ConfigurationVersionID string    `json:"configuration_version_id"`
}

// InsertRun implements Querier.InsertRun.
func (q *DBQuerier) InsertRun(ctx context.Context, params InsertRunParams) (InsertRunRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "InsertRun")
	row := q.conn.QueryRow(ctx, insertRunSQL, params.ID, params.PlanID, params.ApplyID, params.IsDestroy, params.PositionInQueue, params.Refresh, params.RefreshOnly, params.Status, params.PlanStatus, params.ApplyStatus, params.ReplaceAddrs, params.TargetAddrs, params.ConfigurationVersionID, params.WorkspaceID)
	var item InsertRunRow
	if err := row.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanStatus, &item.PlanBin, &item.PlanJson, &item.ApplyStatus, &item.WorkspaceID, &item.ConfigurationVersionID); err != nil {
		return item, fmt.Errorf("query InsertRun: %w", err)
	}
	return item, nil
}

// InsertRunBatch implements Querier.InsertRunBatch.
func (q *DBQuerier) InsertRunBatch(batch genericBatch, params InsertRunParams) {
	batch.Queue(insertRunSQL, params.ID, params.PlanID, params.ApplyID, params.IsDestroy, params.PositionInQueue, params.Refresh, params.RefreshOnly, params.Status, params.PlanStatus, params.ApplyStatus, params.ReplaceAddrs, params.TargetAddrs, params.ConfigurationVersionID, params.WorkspaceID)
}

// InsertRunScan implements Querier.InsertRunScan.
func (q *DBQuerier) InsertRunScan(results pgx.BatchResults) (InsertRunRow, error) {
	row := results.QueryRow()
	var item InsertRunRow
	if err := row.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanStatus, &item.PlanBin, &item.PlanJson, &item.ApplyStatus, &item.WorkspaceID, &item.ConfigurationVersionID); err != nil {
		return item, fmt.Errorf("scan InsertRunBatch row: %w", err)
	}
	return item, nil
}

const insertRunStatusTimestampSQL = `INSERT INTO run_status_timestamps (
    run_id,
    status,
    timestamp
) VALUES (
    $1,
    $2,
    current_timestamp
)
RETURNING *;`

type InsertRunStatusTimestampRow struct {
	RunID     string    `json:"run_id"`
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
}

// InsertRunStatusTimestamp implements Querier.InsertRunStatusTimestamp.
func (q *DBQuerier) InsertRunStatusTimestamp(ctx context.Context, id string, status string) (InsertRunStatusTimestampRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "InsertRunStatusTimestamp")
	row := q.conn.QueryRow(ctx, insertRunStatusTimestampSQL, id, status)
	var item InsertRunStatusTimestampRow
	if err := row.Scan(&item.RunID, &item.Status, &item.Timestamp); err != nil {
		return item, fmt.Errorf("query InsertRunStatusTimestamp: %w", err)
	}
	return item, nil
}

// InsertRunStatusTimestampBatch implements Querier.InsertRunStatusTimestampBatch.
func (q *DBQuerier) InsertRunStatusTimestampBatch(batch genericBatch, id string, status string) {
	batch.Queue(insertRunStatusTimestampSQL, id, status)
}

// InsertRunStatusTimestampScan implements Querier.InsertRunStatusTimestampScan.
func (q *DBQuerier) InsertRunStatusTimestampScan(results pgx.BatchResults) (InsertRunStatusTimestampRow, error) {
	row := results.QueryRow()
	var item InsertRunStatusTimestampRow
	if err := row.Scan(&item.RunID, &item.Status, &item.Timestamp); err != nil {
		return item, fmt.Errorf("scan InsertRunStatusTimestampBatch row: %w", err)
	}
	return item, nil
}

const findRunsByWorkspaceIDSQL = `SELECT
    runs.run_id,
    runs.plan_id,
    runs.apply_id,
    runs.created_at,
    runs.updated_at,
    runs.is_destroy,
    runs.position_in_queue,
    runs.refresh,
    runs.refresh_only,
    runs.status,
    runs.plan_status,
    runs.apply_status,
    runs.replace_addrs,
    runs.target_addrs,
    (plan_resource_reports.*)::"plan_resource_reports" AS plan_resource_report,
    (apply_resource_reports.*)::"apply_resource_reports" AS apply_resource_report,
    (configuration_versions.*)::"configuration_versions" AS configuration_version,
    (workspaces.*)::"workspaces" AS workspace,
    (
        SELECT array_agg(rst.*) AS run_status_timestamps
        FROM run_status_timestamps rst
        WHERE rst.run_id = runs.run_id
        GROUP BY run_id
    ) AS run_status_timestamps,
    (
        SELECT array_agg(pst.*) AS plan_status_timestamps
        FROM plan_status_timestamps pst
        WHERE pst.run_id = runs.run_id
        GROUP BY run_id
    ) AS plan_status_timestamps,
    (
        SELECT array_agg(ast.*) AS apply_status_timestamps
        FROM apply_status_timestamps ast
        WHERE ast.run_id = runs.run_id
        GROUP BY run_id
    ) AS apply_status_timestamps,
    count(*) OVER() AS full_count
FROM runs
LEFT JOIN plan_resource_reports USING(plan_id)
LEFT JOIN apply_resource_reports USING(apply_id)
JOIN configuration_versions USING(workspace_id)
JOIN workspaces USING(workspace_id)
WHERE workspaces.workspace_id = $1
LIMIT $2 OFFSET $3
;`

type FindRunsByWorkspaceIDParams struct {
	WorkspaceID string
	Limit       int
	Offset      int
}

type FindRunsByWorkspaceIDRow struct {
	RunID                 *string                 `json:"run_id"`
	PlanID                *string                 `json:"plan_id"`
	ApplyID               *string                 `json:"apply_id"`
	CreatedAt             time.Time               `json:"created_at"`
	UpdatedAt             time.Time               `json:"updated_at"`
	IsDestroy             *bool                   `json:"is_destroy"`
	PositionInQueue       *int32                  `json:"position_in_queue"`
	Refresh               *bool                   `json:"refresh"`
	RefreshOnly           *bool                   `json:"refresh_only"`
	Status                *string                 `json:"status"`
	PlanStatus            *string                 `json:"plan_status"`
	ApplyStatus           *string                 `json:"apply_status"`
	ReplaceAddrs          []string                `json:"replace_addrs"`
	TargetAddrs           []string                `json:"target_addrs"`
	PlanResourceReport    *otf.ResourceReport     `json:"plan_resource_report"`
	ApplyResourceReport   *otf.ResourceReport     `json:"apply_resource_report"`
	ConfigurationVersion  ConfigurationVersions   `json:"configuration_version"`
	Workspace             Workspaces              `json:"workspace"`
	RunStatusTimestamps   []RunStatusTimestamps   `json:"run_status_timestamps"`
	PlanStatusTimestamps  []PlanStatusTimestamps  `json:"plan_status_timestamps"`
	ApplyStatusTimestamps []ApplyStatusTimestamps `json:"apply_status_timestamps"`
	FullCount             *int                    `json:"full_count"`
}

// FindRunsByWorkspaceID implements Querier.FindRunsByWorkspaceID.
func (q *DBQuerier) FindRunsByWorkspaceID(ctx context.Context, params FindRunsByWorkspaceIDParams) ([]FindRunsByWorkspaceIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindRunsByWorkspaceID")
	rows, err := q.conn.Query(ctx, findRunsByWorkspaceIDSQL, params.WorkspaceID, params.Limit, params.Offset)
	if err != nil {
		return nil, fmt.Errorf("query FindRunsByWorkspaceID: %w", err)
	}
	defer rows.Close()
	items := []FindRunsByWorkspaceIDRow{}
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	for rows.Next() {
		var item FindRunsByWorkspaceIDRow
		if err := rows.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray, &item.FullCount); err != nil {
			return nil, fmt.Errorf("scan FindRunsByWorkspaceID row: %w", err)
		}
		if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceID row: %w", err)
		}
		if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceID row: %w", err)
		}
		if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceID row: %w", err)
		}
		if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceID row: %w", err)
		}
		if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceID row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close FindRunsByWorkspaceID rows: %w", err)
	}
	return items, err
}

// FindRunsByWorkspaceIDBatch implements Querier.FindRunsByWorkspaceIDBatch.
func (q *DBQuerier) FindRunsByWorkspaceIDBatch(batch genericBatch, params FindRunsByWorkspaceIDParams) {
	batch.Queue(findRunsByWorkspaceIDSQL, params.WorkspaceID, params.Limit, params.Offset)
}

// FindRunsByWorkspaceIDScan implements Querier.FindRunsByWorkspaceIDScan.
func (q *DBQuerier) FindRunsByWorkspaceIDScan(results pgx.BatchResults) ([]FindRunsByWorkspaceIDRow, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query FindRunsByWorkspaceIDBatch: %w", err)
	}
	defer rows.Close()
	items := []FindRunsByWorkspaceIDRow{}
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	for rows.Next() {
		var item FindRunsByWorkspaceIDRow
		if err := rows.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray, &item.FullCount); err != nil {
			return nil, fmt.Errorf("scan FindRunsByWorkspaceIDBatch row: %w", err)
		}
		if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceID row: %w", err)
		}
		if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceID row: %w", err)
		}
		if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceID row: %w", err)
		}
		if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceID row: %w", err)
		}
		if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceID row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close FindRunsByWorkspaceIDBatch rows: %w", err)
	}
	return items, err
}

const findRunsByWorkspaceNameSQL = `SELECT
    runs.run_id,
    runs.plan_id,
    runs.apply_id,
    runs.created_at,
    runs.updated_at,
    runs.is_destroy,
    runs.position_in_queue,
    runs.refresh,
    runs.refresh_only,
    runs.status,
    runs.plan_status,
    runs.apply_status,
    runs.replace_addrs,
    runs.target_addrs,
    (plan_resource_reports.*)::"plan_resource_reports" AS plan_resource_report,
    (apply_resource_reports.*)::"apply_resource_reports" AS apply_resource_report,
    (configuration_versions.*)::"configuration_versions" AS configuration_version,
    (workspaces.*)::"workspaces" AS workspace,
    (
        SELECT array_agg(rst.*) AS run_status_timestamps
        FROM run_status_timestamps rst
        WHERE rst.run_id = runs.run_id
        GROUP BY run_id
    ) AS run_status_timestamps,
    (
        SELECT array_agg(pst.*) AS plan_status_timestamps
        FROM plan_status_timestamps pst
        WHERE pst.run_id = runs.run_id
        GROUP BY run_id
    ) AS plan_status_timestamps,
    (
        SELECT array_agg(ast.*) AS apply_status_timestamps
        FROM apply_status_timestamps ast
        WHERE ast.run_id = runs.run_id
        GROUP BY run_id
    ) AS apply_status_timestamps,
    count(*) OVER() AS full_count
FROM runs
LEFT JOIN plan_resource_reports USING(plan_id)
LEFT JOIN apply_resource_reports USING(apply_id)
JOIN configuration_versions USING(workspace_id)
JOIN workspaces USING(workspace_id)
JOIN organizations USING(organization_id)
WHERE workspaces.name = $1
AND organizations.name = $2
LIMIT $3 OFFSET $4
;`

type FindRunsByWorkspaceNameParams struct {
	WorkspaceName    string
	OrganizationName string
	Limit            int
	Offset           int
}

type FindRunsByWorkspaceNameRow struct {
	RunID                 *string                 `json:"run_id"`
	PlanID                *string                 `json:"plan_id"`
	ApplyID               *string                 `json:"apply_id"`
	CreatedAt             time.Time               `json:"created_at"`
	UpdatedAt             time.Time               `json:"updated_at"`
	IsDestroy             *bool                   `json:"is_destroy"`
	PositionInQueue       *int32                  `json:"position_in_queue"`
	Refresh               *bool                   `json:"refresh"`
	RefreshOnly           *bool                   `json:"refresh_only"`
	Status                *string                 `json:"status"`
	PlanStatus            *string                 `json:"plan_status"`
	ApplyStatus           *string                 `json:"apply_status"`
	ReplaceAddrs          []string                `json:"replace_addrs"`
	TargetAddrs           []string                `json:"target_addrs"`
	PlanResourceReport    *otf.ResourceReport     `json:"plan_resource_report"`
	ApplyResourceReport   *otf.ResourceReport     `json:"apply_resource_report"`
	ConfigurationVersion  ConfigurationVersions   `json:"configuration_version"`
	Workspace             Workspaces              `json:"workspace"`
	RunStatusTimestamps   []RunStatusTimestamps   `json:"run_status_timestamps"`
	PlanStatusTimestamps  []PlanStatusTimestamps  `json:"plan_status_timestamps"`
	ApplyStatusTimestamps []ApplyStatusTimestamps `json:"apply_status_timestamps"`
	FullCount             *int                    `json:"full_count"`
}

// FindRunsByWorkspaceName implements Querier.FindRunsByWorkspaceName.
func (q *DBQuerier) FindRunsByWorkspaceName(ctx context.Context, params FindRunsByWorkspaceNameParams) ([]FindRunsByWorkspaceNameRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindRunsByWorkspaceName")
	rows, err := q.conn.Query(ctx, findRunsByWorkspaceNameSQL, params.WorkspaceName, params.OrganizationName, params.Limit, params.Offset)
	if err != nil {
		return nil, fmt.Errorf("query FindRunsByWorkspaceName: %w", err)
	}
	defer rows.Close()
	items := []FindRunsByWorkspaceNameRow{}
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	for rows.Next() {
		var item FindRunsByWorkspaceNameRow
		if err := rows.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray, &item.FullCount); err != nil {
			return nil, fmt.Errorf("scan FindRunsByWorkspaceName row: %w", err)
		}
		if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceName row: %w", err)
		}
		if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceName row: %w", err)
		}
		if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceName row: %w", err)
		}
		if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceName row: %w", err)
		}
		if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceName row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close FindRunsByWorkspaceName rows: %w", err)
	}
	return items, err
}

// FindRunsByWorkspaceNameBatch implements Querier.FindRunsByWorkspaceNameBatch.
func (q *DBQuerier) FindRunsByWorkspaceNameBatch(batch genericBatch, params FindRunsByWorkspaceNameParams) {
	batch.Queue(findRunsByWorkspaceNameSQL, params.WorkspaceName, params.OrganizationName, params.Limit, params.Offset)
}

// FindRunsByWorkspaceNameScan implements Querier.FindRunsByWorkspaceNameScan.
func (q *DBQuerier) FindRunsByWorkspaceNameScan(results pgx.BatchResults) ([]FindRunsByWorkspaceNameRow, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query FindRunsByWorkspaceNameBatch: %w", err)
	}
	defer rows.Close()
	items := []FindRunsByWorkspaceNameRow{}
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	for rows.Next() {
		var item FindRunsByWorkspaceNameRow
		if err := rows.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray, &item.FullCount); err != nil {
			return nil, fmt.Errorf("scan FindRunsByWorkspaceNameBatch row: %w", err)
		}
		if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceName row: %w", err)
		}
		if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceName row: %w", err)
		}
		if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceName row: %w", err)
		}
		if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceName row: %w", err)
		}
		if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByWorkspaceName row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close FindRunsByWorkspaceNameBatch rows: %w", err)
	}
	return items, err
}

const findRunsByStatusesSQL = `SELECT
    runs.run_id,
    runs.plan_id,
    runs.apply_id,
    runs.created_at,
    runs.updated_at,
    runs.is_destroy,
    runs.position_in_queue,
    runs.refresh,
    runs.refresh_only,
    runs.status,
    runs.plan_status,
    runs.apply_status,
    runs.replace_addrs,
    runs.target_addrs,
    (plan_resource_reports.*)::"plan_resource_reports" AS plan_resource_report,
    (apply_resource_reports.*)::"apply_resource_reports" AS apply_resource_report,
    (configuration_versions.*)::"configuration_versions" AS configuration_version,
    (workspaces.*)::"workspaces" AS workspace,
    (
        SELECT array_agg(rst.*) AS run_status_timestamps
        FROM run_status_timestamps rst
        WHERE rst.run_id = runs.run_id
        GROUP BY run_id
    ) AS run_status_timestamps,
    (
        SELECT array_agg(pst.*) AS plan_status_timestamps
        FROM plan_status_timestamps pst
        WHERE pst.run_id = runs.run_id
        GROUP BY run_id
    ) AS plan_status_timestamps,
    (
        SELECT array_agg(ast.*) AS apply_status_timestamps
        FROM apply_status_timestamps ast
        WHERE ast.run_id = runs.run_id
        GROUP BY run_id
    ) AS apply_status_timestamps,
    count(*) OVER() AS full_count
FROM runs
LEFT JOIN plan_resource_reports USING(plan_id)
LEFT JOIN apply_resource_reports USING(apply_id)
JOIN configuration_versions USING(workspace_id)
JOIN workspaces USING(workspace_id)
WHERE runs.status = ANY($1)
LIMIT $2 OFFSET $3
;`

type FindRunsByStatusesParams struct {
	Statuses []string
	Limit    int
	Offset   int
}

type FindRunsByStatusesRow struct {
	RunID                 *string                 `json:"run_id"`
	PlanID                *string                 `json:"plan_id"`
	ApplyID               *string                 `json:"apply_id"`
	CreatedAt             time.Time               `json:"created_at"`
	UpdatedAt             time.Time               `json:"updated_at"`
	IsDestroy             *bool                   `json:"is_destroy"`
	PositionInQueue       *int32                  `json:"position_in_queue"`
	Refresh               *bool                   `json:"refresh"`
	RefreshOnly           *bool                   `json:"refresh_only"`
	Status                *string                 `json:"status"`
	PlanStatus            *string                 `json:"plan_status"`
	ApplyStatus           *string                 `json:"apply_status"`
	ReplaceAddrs          []string                `json:"replace_addrs"`
	TargetAddrs           []string                `json:"target_addrs"`
	PlanResourceReport    *otf.ResourceReport     `json:"plan_resource_report"`
	ApplyResourceReport   *otf.ResourceReport     `json:"apply_resource_report"`
	ConfigurationVersion  ConfigurationVersions   `json:"configuration_version"`
	Workspace             Workspaces              `json:"workspace"`
	RunStatusTimestamps   []RunStatusTimestamps   `json:"run_status_timestamps"`
	PlanStatusTimestamps  []PlanStatusTimestamps  `json:"plan_status_timestamps"`
	ApplyStatusTimestamps []ApplyStatusTimestamps `json:"apply_status_timestamps"`
	FullCount             *int                    `json:"full_count"`
}

// FindRunsByStatuses implements Querier.FindRunsByStatuses.
func (q *DBQuerier) FindRunsByStatuses(ctx context.Context, params FindRunsByStatusesParams) ([]FindRunsByStatusesRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindRunsByStatuses")
	rows, err := q.conn.Query(ctx, findRunsByStatusesSQL, params.Statuses, params.Limit, params.Offset)
	if err != nil {
		return nil, fmt.Errorf("query FindRunsByStatuses: %w", err)
	}
	defer rows.Close()
	items := []FindRunsByStatusesRow{}
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	for rows.Next() {
		var item FindRunsByStatusesRow
		if err := rows.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray, &item.FullCount); err != nil {
			return nil, fmt.Errorf("scan FindRunsByStatuses row: %w", err)
		}
		if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
			return nil, fmt.Errorf("assign FindRunsByStatuses row: %w", err)
		}
		if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
			return nil, fmt.Errorf("assign FindRunsByStatuses row: %w", err)
		}
		if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByStatuses row: %w", err)
		}
		if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByStatuses row: %w", err)
		}
		if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByStatuses row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close FindRunsByStatuses rows: %w", err)
	}
	return items, err
}

// FindRunsByStatusesBatch implements Querier.FindRunsByStatusesBatch.
func (q *DBQuerier) FindRunsByStatusesBatch(batch genericBatch, params FindRunsByStatusesParams) {
	batch.Queue(findRunsByStatusesSQL, params.Statuses, params.Limit, params.Offset)
}

// FindRunsByStatusesScan implements Querier.FindRunsByStatusesScan.
func (q *DBQuerier) FindRunsByStatusesScan(results pgx.BatchResults) ([]FindRunsByStatusesRow, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query FindRunsByStatusesBatch: %w", err)
	}
	defer rows.Close()
	items := []FindRunsByStatusesRow{}
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	for rows.Next() {
		var item FindRunsByStatusesRow
		if err := rows.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray, &item.FullCount); err != nil {
			return nil, fmt.Errorf("scan FindRunsByStatusesBatch row: %w", err)
		}
		if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
			return nil, fmt.Errorf("assign FindRunsByStatuses row: %w", err)
		}
		if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
			return nil, fmt.Errorf("assign FindRunsByStatuses row: %w", err)
		}
		if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByStatuses row: %w", err)
		}
		if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByStatuses row: %w", err)
		}
		if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
			return nil, fmt.Errorf("assign FindRunsByStatuses row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close FindRunsByStatusesBatch rows: %w", err)
	}
	return items, err
}

const findRunByIDSQL = `SELECT
    runs.run_id,
    runs.plan_id,
    runs.apply_id,
    runs.created_at,
    runs.updated_at,
    runs.is_destroy,
    runs.position_in_queue,
    runs.refresh,
    runs.refresh_only,
    runs.status,
    runs.plan_status,
    runs.apply_status,
    runs.replace_addrs,
    runs.target_addrs,
    (plan_resource_reports.*)::"plan_resource_reports" AS plan_resource_report,
    (apply_resource_reports.*)::"apply_resource_reports" AS apply_resource_report,
    (configuration_versions.*)::"configuration_versions" AS configuration_version,
    (workspaces.*)::"workspaces" AS workspace,
    (
        SELECT array_agg(rst.*) AS run_status_timestamps
        FROM run_status_timestamps rst
        WHERE rst.run_id = runs.run_id
        GROUP BY run_id
    ) AS run_status_timestamps,
    (
        SELECT array_agg(pst.*) AS plan_status_timestamps
        FROM plan_status_timestamps pst
        WHERE pst.run_id = runs.run_id
        GROUP BY run_id
    ) AS plan_status_timestamps,
    (
        SELECT array_agg(ast.*) AS apply_status_timestamps
        FROM apply_status_timestamps ast
        WHERE ast.run_id = runs.run_id
        GROUP BY run_id
    ) AS apply_status_timestamps
FROM runs
LEFT JOIN plan_resource_reports USING(plan_id)
LEFT JOIN apply_resource_reports USING(apply_id)
JOIN configuration_versions USING(workspace_id)
JOIN workspaces USING(workspace_id)
WHERE runs.run_id = $1
;`

type FindRunByIDRow struct {
	RunID                 *string                 `json:"run_id"`
	PlanID                *string                 `json:"plan_id"`
	ApplyID               *string                 `json:"apply_id"`
	CreatedAt             time.Time               `json:"created_at"`
	UpdatedAt             time.Time               `json:"updated_at"`
	IsDestroy             *bool                   `json:"is_destroy"`
	PositionInQueue       *int32                  `json:"position_in_queue"`
	Refresh               *bool                   `json:"refresh"`
	RefreshOnly           *bool                   `json:"refresh_only"`
	Status                *string                 `json:"status"`
	PlanStatus            *string                 `json:"plan_status"`
	ApplyStatus           *string                 `json:"apply_status"`
	ReplaceAddrs          []string                `json:"replace_addrs"`
	TargetAddrs           []string                `json:"target_addrs"`
	PlanResourceReport    *otf.ResourceReport     `json:"plan_resource_report"`
	ApplyResourceReport   *otf.ResourceReport     `json:"apply_resource_report"`
	ConfigurationVersion  ConfigurationVersions   `json:"configuration_version"`
	Workspace             Workspaces              `json:"workspace"`
	RunStatusTimestamps   []RunStatusTimestamps   `json:"run_status_timestamps"`
	PlanStatusTimestamps  []PlanStatusTimestamps  `json:"plan_status_timestamps"`
	ApplyStatusTimestamps []ApplyStatusTimestamps `json:"apply_status_timestamps"`
}

// FindRunByID implements Querier.FindRunByID.
func (q *DBQuerier) FindRunByID(ctx context.Context, runID string) (FindRunByIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindRunByID")
	row := q.conn.QueryRow(ctx, findRunByIDSQL, runID)
	var item FindRunByIDRow
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	if err := row.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray); err != nil {
		return item, fmt.Errorf("query FindRunByID: %w", err)
	}
	if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
		return item, fmt.Errorf("assign FindRunByID row: %w", err)
	}
	if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
		return item, fmt.Errorf("assign FindRunByID row: %w", err)
	}
	if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByID row: %w", err)
	}
	if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByID row: %w", err)
	}
	if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByID row: %w", err)
	}
	return item, nil
}

// FindRunByIDBatch implements Querier.FindRunByIDBatch.
func (q *DBQuerier) FindRunByIDBatch(batch genericBatch, runID string) {
	batch.Queue(findRunByIDSQL, runID)
}

// FindRunByIDScan implements Querier.FindRunByIDScan.
func (q *DBQuerier) FindRunByIDScan(results pgx.BatchResults) (FindRunByIDRow, error) {
	row := results.QueryRow()
	var item FindRunByIDRow
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	if err := row.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray); err != nil {
		return item, fmt.Errorf("scan FindRunByIDBatch row: %w", err)
	}
	if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
		return item, fmt.Errorf("assign FindRunByID row: %w", err)
	}
	if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
		return item, fmt.Errorf("assign FindRunByID row: %w", err)
	}
	if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByID row: %w", err)
	}
	if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByID row: %w", err)
	}
	if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByID row: %w", err)
	}
	return item, nil
}

const findRunByPlanIDSQL = `SELECT
    runs.run_id,
    runs.plan_id,
    runs.apply_id,
    runs.created_at,
    runs.updated_at,
    runs.is_destroy,
    runs.position_in_queue,
    runs.refresh,
    runs.refresh_only,
    runs.status,
    runs.plan_status,
    runs.apply_status,
    runs.replace_addrs,
    runs.target_addrs,
    (plan_resource_reports.*)::"plan_resource_reports" AS plan_resource_report,
    (apply_resource_reports.*)::"apply_resource_reports" AS apply_resource_report,
    (configuration_versions.*)::"configuration_versions" AS configuration_version,
    (workspaces.*)::"workspaces" AS workspace,
    (
        SELECT array_agg(rst.*) AS run_status_timestamps
        FROM run_status_timestamps rst
        WHERE rst.run_id = runs.run_id
        GROUP BY run_id
    ) AS run_status_timestamps,
    (
        SELECT array_agg(pst.*) AS plan_status_timestamps
        FROM plan_status_timestamps pst
        WHERE pst.run_id = runs.run_id
        GROUP BY run_id
    ) AS plan_status_timestamps,
    (
        SELECT array_agg(ast.*) AS apply_status_timestamps
        FROM apply_status_timestamps ast
        WHERE ast.run_id = runs.run_id
        GROUP BY run_id
    ) AS apply_status_timestamps
FROM runs
LEFT JOIN plan_resource_reports USING(plan_id)
LEFT JOIN apply_resource_reports USING(apply_id)
JOIN configuration_versions USING(workspace_id)
JOIN workspaces USING(workspace_id)
WHERE runs.plan_id = $1
;`

type FindRunByPlanIDRow struct {
	RunID                 *string                 `json:"run_id"`
	PlanID                *string                 `json:"plan_id"`
	ApplyID               *string                 `json:"apply_id"`
	CreatedAt             time.Time               `json:"created_at"`
	UpdatedAt             time.Time               `json:"updated_at"`
	IsDestroy             *bool                   `json:"is_destroy"`
	PositionInQueue       *int32                  `json:"position_in_queue"`
	Refresh               *bool                   `json:"refresh"`
	RefreshOnly           *bool                   `json:"refresh_only"`
	Status                *string                 `json:"status"`
	PlanStatus            *string                 `json:"plan_status"`
	ApplyStatus           *string                 `json:"apply_status"`
	ReplaceAddrs          []string                `json:"replace_addrs"`
	TargetAddrs           []string                `json:"target_addrs"`
	PlanResourceReport    *otf.ResourceReport     `json:"plan_resource_report"`
	ApplyResourceReport   *otf.ResourceReport     `json:"apply_resource_report"`
	ConfigurationVersion  ConfigurationVersions   `json:"configuration_version"`
	Workspace             Workspaces              `json:"workspace"`
	RunStatusTimestamps   []RunStatusTimestamps   `json:"run_status_timestamps"`
	PlanStatusTimestamps  []PlanStatusTimestamps  `json:"plan_status_timestamps"`
	ApplyStatusTimestamps []ApplyStatusTimestamps `json:"apply_status_timestamps"`
}

// FindRunByPlanID implements Querier.FindRunByPlanID.
func (q *DBQuerier) FindRunByPlanID(ctx context.Context, planID string) (FindRunByPlanIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindRunByPlanID")
	row := q.conn.QueryRow(ctx, findRunByPlanIDSQL, planID)
	var item FindRunByPlanIDRow
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	if err := row.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray); err != nil {
		return item, fmt.Errorf("query FindRunByPlanID: %w", err)
	}
	if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
		return item, fmt.Errorf("assign FindRunByPlanID row: %w", err)
	}
	if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
		return item, fmt.Errorf("assign FindRunByPlanID row: %w", err)
	}
	if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByPlanID row: %w", err)
	}
	if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByPlanID row: %w", err)
	}
	if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByPlanID row: %w", err)
	}
	return item, nil
}

// FindRunByPlanIDBatch implements Querier.FindRunByPlanIDBatch.
func (q *DBQuerier) FindRunByPlanIDBatch(batch genericBatch, planID string) {
	batch.Queue(findRunByPlanIDSQL, planID)
}

// FindRunByPlanIDScan implements Querier.FindRunByPlanIDScan.
func (q *DBQuerier) FindRunByPlanIDScan(results pgx.BatchResults) (FindRunByPlanIDRow, error) {
	row := results.QueryRow()
	var item FindRunByPlanIDRow
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	if err := row.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray); err != nil {
		return item, fmt.Errorf("scan FindRunByPlanIDBatch row: %w", err)
	}
	if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
		return item, fmt.Errorf("assign FindRunByPlanID row: %w", err)
	}
	if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
		return item, fmt.Errorf("assign FindRunByPlanID row: %w", err)
	}
	if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByPlanID row: %w", err)
	}
	if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByPlanID row: %w", err)
	}
	if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByPlanID row: %w", err)
	}
	return item, nil
}

const findRunByApplyIDSQL = `SELECT
    runs.run_id,
    runs.plan_id,
    runs.apply_id,
    runs.created_at,
    runs.updated_at,
    runs.is_destroy,
    runs.position_in_queue,
    runs.refresh,
    runs.refresh_only,
    runs.status,
    runs.plan_status,
    runs.apply_status,
    runs.replace_addrs,
    runs.target_addrs,
    (plan_resource_reports.*)::"plan_resource_reports" AS plan_resource_report,
    (apply_resource_reports.*)::"apply_resource_reports" AS apply_resource_report,
    (configuration_versions.*)::"configuration_versions" AS configuration_version,
    (workspaces.*)::"workspaces" AS workspace,
    (
        SELECT array_agg(rst.*) AS run_status_timestamps
        FROM run_status_timestamps rst
        WHERE rst.run_id = runs.run_id
        GROUP BY run_id
    ) AS run_status_timestamps,
    (
        SELECT array_agg(pst.*) AS plan_status_timestamps
        FROM plan_status_timestamps pst
        WHERE pst.run_id = runs.run_id
        GROUP BY run_id
    ) AS plan_status_timestamps,
    (
        SELECT array_agg(ast.*) AS apply_status_timestamps
        FROM apply_status_timestamps ast
        WHERE ast.run_id = runs.run_id
        GROUP BY run_id
    ) AS apply_status_timestamps
FROM runs
LEFT JOIN plan_resource_reports USING(plan_id)
LEFT JOIN apply_resource_reports USING(apply_id)
JOIN configuration_versions USING(workspace_id)
JOIN workspaces USING(workspace_id)
WHERE runs.apply_id = $1
;`

type FindRunByApplyIDRow struct {
	RunID                 *string                 `json:"run_id"`
	PlanID                *string                 `json:"plan_id"`
	ApplyID               *string                 `json:"apply_id"`
	CreatedAt             time.Time               `json:"created_at"`
	UpdatedAt             time.Time               `json:"updated_at"`
	IsDestroy             *bool                   `json:"is_destroy"`
	PositionInQueue       *int32                  `json:"position_in_queue"`
	Refresh               *bool                   `json:"refresh"`
	RefreshOnly           *bool                   `json:"refresh_only"`
	Status                *string                 `json:"status"`
	PlanStatus            *string                 `json:"plan_status"`
	ApplyStatus           *string                 `json:"apply_status"`
	ReplaceAddrs          []string                `json:"replace_addrs"`
	TargetAddrs           []string                `json:"target_addrs"`
	PlanResourceReport    *otf.ResourceReport     `json:"plan_resource_report"`
	ApplyResourceReport   *otf.ResourceReport     `json:"apply_resource_report"`
	ConfigurationVersion  ConfigurationVersions   `json:"configuration_version"`
	Workspace             Workspaces              `json:"workspace"`
	RunStatusTimestamps   []RunStatusTimestamps   `json:"run_status_timestamps"`
	PlanStatusTimestamps  []PlanStatusTimestamps  `json:"plan_status_timestamps"`
	ApplyStatusTimestamps []ApplyStatusTimestamps `json:"apply_status_timestamps"`
}

// FindRunByApplyID implements Querier.FindRunByApplyID.
func (q *DBQuerier) FindRunByApplyID(ctx context.Context, applyID string) (FindRunByApplyIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindRunByApplyID")
	row := q.conn.QueryRow(ctx, findRunByApplyIDSQL, applyID)
	var item FindRunByApplyIDRow
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	if err := row.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray); err != nil {
		return item, fmt.Errorf("query FindRunByApplyID: %w", err)
	}
	if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
		return item, fmt.Errorf("assign FindRunByApplyID row: %w", err)
	}
	if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
		return item, fmt.Errorf("assign FindRunByApplyID row: %w", err)
	}
	if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByApplyID row: %w", err)
	}
	if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByApplyID row: %w", err)
	}
	if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByApplyID row: %w", err)
	}
	return item, nil
}

// FindRunByApplyIDBatch implements Querier.FindRunByApplyIDBatch.
func (q *DBQuerier) FindRunByApplyIDBatch(batch genericBatch, applyID string) {
	batch.Queue(findRunByApplyIDSQL, applyID)
}

// FindRunByApplyIDScan implements Querier.FindRunByApplyIDScan.
func (q *DBQuerier) FindRunByApplyIDScan(results pgx.BatchResults) (FindRunByApplyIDRow, error) {
	row := results.QueryRow()
	var item FindRunByApplyIDRow
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	if err := row.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, &item.PlanResourceReport, &item.ApplyResourceReport, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray); err != nil {
		return item, fmt.Errorf("scan FindRunByApplyIDBatch row: %w", err)
	}
	if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
		return item, fmt.Errorf("assign FindRunByApplyID row: %w", err)
	}
	if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
		return item, fmt.Errorf("assign FindRunByApplyID row: %w", err)
	}
	if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByApplyID row: %w", err)
	}
	if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByApplyID row: %w", err)
	}
	if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByApplyID row: %w", err)
	}
	return item, nil
}

const findRunByIDForUpdateSQL = `SELECT
    runs.run_id,
    runs.plan_id,
    runs.apply_id,
    runs.created_at,
    runs.updated_at,
    runs.is_destroy,
    runs.position_in_queue,
    runs.refresh,
    runs.refresh_only,
    runs.status,
    runs.plan_status,
    runs.apply_status,
    runs.replace_addrs,
    runs.target_addrs,
    (configuration_versions.*)::"configuration_versions" AS configuration_version,
    (workspaces.*)::"workspaces" AS workspace,
    (
        SELECT array_agg(rst.*) AS run_status_timestamps
        FROM run_status_timestamps rst
        WHERE rst.run_id = runs.run_id
        GROUP BY run_id
    ) AS run_status_timestamps,
    (
        SELECT array_agg(pst.*) AS plan_status_timestamps
        FROM plan_status_timestamps pst
        WHERE pst.run_id = runs.run_id
        GROUP BY run_id
    ) AS plan_status_timestamps,
    (
        SELECT array_agg(ast.*) AS apply_status_timestamps
        FROM apply_status_timestamps ast
        WHERE ast.run_id = runs.run_id
        GROUP BY run_id
    ) AS apply_status_timestamps
FROM runs
JOIN configuration_versions USING(workspace_id)
JOIN workspaces USING(workspace_id)
WHERE runs.run_id = $1
FOR UPDATE
;`

type FindRunByIDForUpdateRow struct {
	RunID                 *string                 `json:"run_id"`
	PlanID                *string                 `json:"plan_id"`
	ApplyID               *string                 `json:"apply_id"`
	CreatedAt             time.Time               `json:"created_at"`
	UpdatedAt             time.Time               `json:"updated_at"`
	IsDestroy             *bool                   `json:"is_destroy"`
	PositionInQueue       *int32                  `json:"position_in_queue"`
	Refresh               *bool                   `json:"refresh"`
	RefreshOnly           *bool                   `json:"refresh_only"`
	Status                *string                 `json:"status"`
	PlanStatus            *string                 `json:"plan_status"`
	ApplyStatus           *string                 `json:"apply_status"`
	ReplaceAddrs          []string                `json:"replace_addrs"`
	TargetAddrs           []string                `json:"target_addrs"`
	ConfigurationVersion  ConfigurationVersions   `json:"configuration_version"`
	Workspace             Workspaces              `json:"workspace"`
	RunStatusTimestamps   []RunStatusTimestamps   `json:"run_status_timestamps"`
	PlanStatusTimestamps  []PlanStatusTimestamps  `json:"plan_status_timestamps"`
	ApplyStatusTimestamps []ApplyStatusTimestamps `json:"apply_status_timestamps"`
}

// FindRunByIDForUpdate implements Querier.FindRunByIDForUpdate.
func (q *DBQuerier) FindRunByIDForUpdate(ctx context.Context, runID string) (FindRunByIDForUpdateRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindRunByIDForUpdate")
	row := q.conn.QueryRow(ctx, findRunByIDForUpdateSQL, runID)
	var item FindRunByIDForUpdateRow
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	if err := row.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray); err != nil {
		return item, fmt.Errorf("query FindRunByIDForUpdate: %w", err)
	}
	if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
		return item, fmt.Errorf("assign FindRunByIDForUpdate row: %w", err)
	}
	if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
		return item, fmt.Errorf("assign FindRunByIDForUpdate row: %w", err)
	}
	if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByIDForUpdate row: %w", err)
	}
	if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByIDForUpdate row: %w", err)
	}
	if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByIDForUpdate row: %w", err)
	}
	return item, nil
}

// FindRunByIDForUpdateBatch implements Querier.FindRunByIDForUpdateBatch.
func (q *DBQuerier) FindRunByIDForUpdateBatch(batch genericBatch, runID string) {
	batch.Queue(findRunByIDForUpdateSQL, runID)
}

// FindRunByIDForUpdateScan implements Querier.FindRunByIDForUpdateScan.
func (q *DBQuerier) FindRunByIDForUpdateScan(results pgx.BatchResults) (FindRunByIDForUpdateRow, error) {
	row := results.QueryRow()
	var item FindRunByIDForUpdateRow
	configurationVersionRow := q.types.newConfigurationVersions()
	workspaceRow := q.types.newWorkspaces()
	runStatusTimestampsArray := q.types.newRunStatusTimestampsArray()
	planStatusTimestampsArray := q.types.newPlanStatusTimestampsArray()
	applyStatusTimestampsArray := q.types.newApplyStatusTimestampsArray()
	if err := row.Scan(&item.RunID, &item.PlanID, &item.ApplyID, &item.CreatedAt, &item.UpdatedAt, &item.IsDestroy, &item.PositionInQueue, &item.Refresh, &item.RefreshOnly, &item.Status, &item.PlanStatus, &item.ApplyStatus, &item.ReplaceAddrs, &item.TargetAddrs, configurationVersionRow, workspaceRow, runStatusTimestampsArray, planStatusTimestampsArray, applyStatusTimestampsArray); err != nil {
		return item, fmt.Errorf("scan FindRunByIDForUpdateBatch row: %w", err)
	}
	if err := configurationVersionRow.AssignTo(&item.ConfigurationVersion); err != nil {
		return item, fmt.Errorf("assign FindRunByIDForUpdate row: %w", err)
	}
	if err := workspaceRow.AssignTo(&item.Workspace); err != nil {
		return item, fmt.Errorf("assign FindRunByIDForUpdate row: %w", err)
	}
	if err := runStatusTimestampsArray.AssignTo(&item.RunStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByIDForUpdate row: %w", err)
	}
	if err := planStatusTimestampsArray.AssignTo(&item.PlanStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByIDForUpdate row: %w", err)
	}
	if err := applyStatusTimestampsArray.AssignTo(&item.ApplyStatusTimestamps); err != nil {
		return item, fmt.Errorf("assign FindRunByIDForUpdate row: %w", err)
	}
	return item, nil
}

const updateRunStatusSQL = `UPDATE runs
SET
    status = $1,
    updated_at = current_timestamp
WHERE run_id = $2
RETURNING updated_at
;`

// UpdateRunStatus implements Querier.UpdateRunStatus.
func (q *DBQuerier) UpdateRunStatus(ctx context.Context, status string, id string) (time.Time, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "UpdateRunStatus")
	row := q.conn.QueryRow(ctx, updateRunStatusSQL, status, id)
	var item time.Time
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("query UpdateRunStatus: %w", err)
	}
	return item, nil
}

// UpdateRunStatusBatch implements Querier.UpdateRunStatusBatch.
func (q *DBQuerier) UpdateRunStatusBatch(batch genericBatch, status string, id string) {
	batch.Queue(updateRunStatusSQL, status, id)
}

// UpdateRunStatusScan implements Querier.UpdateRunStatusScan.
func (q *DBQuerier) UpdateRunStatusScan(results pgx.BatchResults) (time.Time, error) {
	row := results.QueryRow()
	var item time.Time
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("scan UpdateRunStatusBatch row: %w", err)
	}
	return item, nil
}

const deleteRunByIDSQL = `DELETE
FROM runs
WHERE run_id = $1;`

// DeleteRunByID implements Querier.DeleteRunByID.
func (q *DBQuerier) DeleteRunByID(ctx context.Context, runID string) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "DeleteRunByID")
	cmdTag, err := q.conn.Exec(ctx, deleteRunByIDSQL, runID)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query DeleteRunByID: %w", err)
	}
	return cmdTag, err
}

// DeleteRunByIDBatch implements Querier.DeleteRunByIDBatch.
func (q *DBQuerier) DeleteRunByIDBatch(batch genericBatch, runID string) {
	batch.Queue(deleteRunByIDSQL, runID)
}

// DeleteRunByIDScan implements Querier.DeleteRunByIDScan.
func (q *DBQuerier) DeleteRunByIDScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec DeleteRunByIDBatch: %w", err)
	}
	return cmdTag, err
}
