name: chart

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          repository: leg100/otf-charts
      -
        name: Bump version
        run: |
          # set app version to the value of the tag, stripping off the 'v'
          tag=${{ github.ref_name }}
          appVersion=${tag#v}
          yq -i ".appVersion = \"${appVersion}\"" ./charts/otf/Chart.yaml
          # bump patch in chart version
          yq -i '.version |= (split(".") | .[-1] |= ((. tag = "!!int") + 1) | join("."))' ./charts/otf/Chart.yaml
          # create branch and commit
          git config --global user.email "chart-bumper@otf.ninja"
          git config --global user.name "Chart bumper"
          git checkout -b new-otf-version-${{ github.ref_name }}
          git add ./charts/otf/Chart.yaml
          git commit -m "New otf version ${{ github.ref_name }}"
      -
        name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: new-otf-version-${{ github.ref_name }}
          destination_branch: master
          pr_title: "New OTF version: ${{ github.ref_name }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_body: This is an automated PR triggered by a new release of OTF.
